### ISSUE TITLE
Enhancement - Maintain persistent fileshare address after adding files.

### ISSUE THREAD

**Issue by AngelHair** [onionshare/onionshare#1338]
I have been using the new OnionShare CLI 2.3.1 on a Raspberry Pi, using Ubuntu and I think I may have found a bug, or possibly just room for improvement.

Ubuntu 20.04.2 LTS
Linux 5.4.0-1034-raspi

I have been trying the persistent filesharing mode with the following command string:

/home/fileshare01/.local/bin/onionshare-cli --no-autostop-sharing /home/fileshare01/files_to_share/* --persistent fileshare.session

The issue is when I add files to the ".../files_to_share" folder, they do not show up when I access the persistent .onion address.  It appears the list of files to share is in the "persist.session" file, which also contains the data needed to re-create the .onion address.

If I remove the "persist.session" file, the new files show up, but with a new .onion address, which seems to defeat the persistence function.

(I am not sure if this persistence issue would affect the webserver mode, but I suspect it might, since it seems the website files are kept in the "persist.session" file in that mode, as well.)

Also, I see a "--public" option for use without a password, but it seems to operate just fine with no password without using the "--public" option, and I did not see any way to add a password.

**Comment by mig5** [comment]
Hi @AngelHair , thanks for the report!

Re: the first issue, are you saying that you started a share, then tried to add files whilst the share was already running, and expected to see those files appear in the already-running share?

If I've understood that right, then that's a known current limitation of OnionShare: any changes to those shared files (added, removed, changed in some way) are only seen if you stop the share first and then start it again after having made those changes. I think this is because OnionShare isn't actually sharing the *original* files, it's copied them to a temporary area and shared the *temp* files. 

We have an existing story for that in https://github.com/micahflee/onionshare/issues/1059 and someone is working on a PR for it here if you were interested in trying it (though it's not yet finished): https://github.com/micahflee/onionshare/pull/1256

It isn't an issue with the 'persistent' mode but due to the way OnionShare loads the files for sharing, it doesn't keep 'watching' those original files.

Re the second issue:

> Also, I see a "--public" option for use without a password, but it seems to operate just fine with no password without using the "--public" option, and I did not see any way to add a password.

This seems strange if you don't see a password without specifying --public. The username/password is 'basic auth' and it appears at the start of the onion URL, e.g `http://onionshare:SOME-PASSWORD@[the onion address]`. This isn't the case for you?  You may be expecting that you are able to supply a password of your own, which is not the intention of the feature - it generates a random password for you. Hope that clears that up!

**Comment by mig5** [comment]
I'm going to close this, after testing, as I think it's a misunderstanding of the current functionality, or at least a duplicate:

> The issue is when I add files to the ".../files_to_share" folder, they do not show up when I access the persistent .onion address.

If it is a running share, it doesn't automatically detect when you add more files into the "../files_to_share" folder. You have to stop the running share and restart it for it to pick up the new files you've added since you last started the share. 

(The use of the persistent mode is convenient here because next time you start up the share, it uses the same address. So aside from the slight inconvenience of stopping the running share and restarting it, it's not that big a deal)

We already have an enhancement ticket for allowing OnionShare to automatically detect new files (or changes to files) while the share is running: https://github.com/onionshare/onionshare/issues/1059 . That is mostly relevant for Website mode, or share mode where 'autostop after first download' isn't enabled (like your case). Your feature request is the same as that ticket, so I'll close this as a duplicate

> Also, I see a "--public" option for use without a password, but it seems to operate just fine with no password without using the "--public" option, and I did not see any way to add a password.

This is a misunderstanding. By default OnionShare 2.3.2 and earlier used HTTP 'basic' authentication, which adds the username:password to the front of the URL for convenience (browsers understand how to authenticate when they see that format). You don't get to choose the password, a random one is selected. This is all documented at https://docs.onionshare.org.

Using public mode disables the use of basic auth. You probably just didn't notice the username/password basic auth string was part of the URL.

OnionShare 2.4 and higher will no longer use a 'password' but instead default to using 'Client Authentication' (use of a private key, at the onion layer). Public mode will still turn that off.

Hope that clears up the confusion! I agree being able to see new files in a folder you're already sharing, would be a good usability improvement, but the functionality doesn't yet work that way. 

In the meantime, if you're using persistent mode, stop and start the share and the recently-added files should now be present in the share. I've just tested this and it works fine.
