### ISSUE TITLE
Chat: Send offline messages

### ISSUE THREAD

**Issue by lucy2812** [onionshare/onionshare#1381]
I want to send a user a message when they are offline.

**Comment by mig5** [comment]
The onion service runs on the OnionShare user's machine.

There are no intermediary servers unlike WhatsApp, Signal etc. This is a security feature.

To support this, we would have to move the onion service to be an always-on server in the middle to intercept (and therefore 'hold') messages.

I don't think we should do this, because OnionShare's security model is precisely that there is no 'man in the middle'.

**Comment by lucy2812** [comment]
Are/could the messages be held in the self-hosted "chat server"?

**Comment by micahflee** [comment]
> Are/could the messages be held in the self-hosted "chat server"?

If the user is offline then the chat server would also be offline, so it just wouldn't be able to load in Tor Browser.
