### ISSUE TITLE
Onionsite invalid?

### ISSUE THREAD

**Issue by Heisenberg702** [onionshare/onionshare#1407]
Error says invalid onionsite address but I typed it correctly. I’m not very familiar with this so what am I missing here?

**Comment by mig5** [comment]
'Invalid onion' in Tor Browser does usually mean you somehow typed the wrong address, I'm afraid. That's the only time I've seen that message (it's not the same message as when your onion site simply isn't running).

If you are typing the address out by hand, be careful to avoid common traps such as typing I (upper case i) instead of 'l' (lower case L).

I often reproduce this error when typing it out by hand and missing one character. The onion address should be 56 characters (without the .onion or the `http://onionshare:xxxxx-xxxx@` bits at the start).

If you keep reproducing it, can you start a demo onion service without any sensitive documents shared, and paste the onion address here for us to try hitting it?

**Comment by AlexDeMoura** [comment]
I know this thread is closed, but I will try anyway in the hope this could be of any help.
V2 Onion Services/addresses are deprecated for security reasons - V2 Onion address: {*16-char length*}.onion
The current version is V3 Onion address: {*56-char length*}.onion
- September 2020: warning onion service operators and clients that V2 will be deprecated and obsolete;
- June 2021: warning users;
- July 2021: Tor will no longer support V2;
- October 2021: Tor client disables V2;
Detailed information: https://support.torproject.org/onionservices/v2-deprecation/
Of course many sites have links (or copy/paste strings) with V2 addresses. Websites could be redirected from V2 to V3 BUT  until the V2 onion address becomes unreachable, the users were encourage to update their bookmarks. As far as I know, there is no V2-to-V3 convert database to help users to find V3 addresses of previous (V2) Onion sites.
It is advised to use a Tor client search engine until find a V3 address of a required website. it is sad... but it is safer.
