### ISSUE TITLE
Must upload stem fork to PyPi

### ISSUE THREAD

**Issue by micahflee** [onionshare/onionshare#1435]
I'm working on making the version 2.4 release and I just hit a snag with publishing to PyPi:

```
$ poetry publish --build
There are 2 files ready for publishing. Build anyway? (yes/no) [no] yes
Building onionshare_cli (2.4)
  - Building sdist
  - Built onionshare_cli-2.4.tar.gz
  - Building wheel
  - Built onionshare_cli-2.4-py3-none-any.whl

Username: micahflee
Password: 
Publishing onionshare_cli (2.4) to PyPI
 - Uploading onionshare_cli-2.4-py3-none-any.whl 100%

  UploadError

  HTTP Error 400: Invalid value for requires_dist. Error: Can't have direct dependency: 'stem @ git+https://github.com/onionshare/stem.git@1.8.1'

  at ~/.local/lib/python3.9/site-packages/poetry/publishing/uploader.py:216 in _upload
      212│                     self._register(session, url)
      213│                 except HTTPError as e:
      214│                     raise UploadError(e)
      215│ 
    → 216│             raise UploadError(e)
      217│ 
      218│     def _do_upload(
      219│         self, session, url, dry_run=False
      220│     ):  # type: (requests.Session, str, Optional[bool]) -> None
```

PyPi doesn't support git repo dependencies, so we can't publish onionshare 2.4 there.

For this to work, we'll need to upload stem 1.8.1 to PyPi, but the name `stem` is reserved for the original project, and this is a fork. So I guess we'll need to rename it?

What are your thoughts @mig5 @SaptakS ?

**Comment by micahflee** [comment]
Ugh, running into a similar problem making the flatpak package. I should be able to work around that one though.

**Comment by mig5** [comment]
I think we may as well fork in PyPi, because I can see there are other things we could add to our 1.8.x branch, so the fork might end up living for a bit longer than I originally hoped. 

For example, the client-side attaching of the private key to an onion in Stem in order to connect to a client-auth-protected onion - which was [actually my first Stem patch](https://github.com/torproject/stem/issues/66).

I actually did this in a local branch which allowed me to do a rough, simple CLI prototype of https://github.com/onionshare/onionshare/issues/365 a month or so ago.

That work had previously got merged in to Stem, but against master branch, which was then so radically refactored it stopped working (and then work on Stem seemed to cease). So it's an example of something we could re-introduce to the 1.8.x branch if we were to maintain it a bit longer.

**Comment by SaptakS** [comment]
I think since stem is not being maintained right now and we are still using it for onionshare and will be using for the forseeable future, it makes sense to rename and fork it in PyPi. So I agree with both of you.

**Comment by micahflee** [comment]
Our stem fork has been renamed to cepa and is uploaded to PyPi:

https://github.com/onionshare/cepa
https://pypi.org/project/cepa/

**Comment by micahflee** [comment]
There is a strange problem with `cepa` though. Using stem, I can authenticate to my Tor Browser's tor:

```
(stem-venv) user@night ~/tmp $ python
Python 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from stem.control import Controller
>>> c = Controller.from_port(port=9151)
>>> c.authenticate()
>>> 
```

Using `cepa`, I can't. It hangs forever on `c.authenticate()`:

```
(cepa-venv) user@night ~/tmp $ python
Python 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from stem.control import Controller
>>> c = Controller.from_port(port=9151)
>>> c.authenticate()
```

**Comment by micahflee** [comment]
I made a `cepa` release 1.8.3 based off the `maint` branch instead of `master`, and confirmed that this fixes the problem.
