### ISSUE TITLE
Onionshare portable / runnable fom USB flash drive? How to start?

### ISSUE THREAD

**Issue by tobwz** [onionshare/onionshare#1436]
Can I install OnionShare on an USB Flash Drive and run it on arbitrary computers?

Is there a portable OnionShare install?

Assume I install it "normally" on Windows: How should I start OnionShare?

Toby

**Comment by mig5** [comment]
> Can I install OnionShare on an USB Flash Drive and run it on arbitrary computers?
>
> Is there a portable OnionShare install?

Not yet, but hopefully some day. See https://github.com/onionshare/onionshare/issues/367

> Assume I install it "normally" on Windows: How should I start OnionShare?

After installing it normally, it should be in your list of programs accessible from your desktop menu, like any other program on Windows.

**Comment by tobwz** [comment]
Hmm, I tried Workaround from webpage https://github.com/onionshare/onionshare/issues/367:

"Decompress the program with 7zip (http://www.7-zip.org) and launch onionshare-gui.exe."

But (at least in newest v2.4) there is no such file as onionshare-gui.exe

Where is it?

**Comment by mig5** [comment]
That workaround dates from about 4 years ago - unfortunately I don't think it will work anymore as the packaging is very different these days.

I took a look in an extracted copy of the .msi file, and there *is* an exe for the 'cli' version in there, but not sure if it will still work as a standalone exe. I don't have a windows machine to try it.

If you need a portable version of OnionShare you could consider running the Tails Linux live distribution, which might allow saving the OnionShare config to a 'persistent' volume (on a USB stick), but a) I haven't tested that and b) it will be an older OnionShare version because Tails/Debian lags behind.

Sorry for the inconvenience. It's a big job to make a portable version and no-one has had time yet. Contributions are welcome of course.

**Comment by mig5** [comment]
Closing in favour of #367
