### ISSUE TITLE
Incorrect MIME setting in operating system causes Flask to share javascript files as text/plain and breaks Chat

### ISSUE THREAD

**Issue by goodusername99** [onionshare/onionshare#1443]
When trying to use an onionshare chatroom, no textboxes or other visuals besides the logo and basic elements are loading.

![image](https://user-images.githubusercontent.com/92353038/136893085-3edcc3dd-5d97-416a-919a-e25477fe06e9.png)

From what I can tell, it looks like there is some sort of formatting error with the js.

![image](https://user-images.githubusercontent.com/92353038/136893156-cb807ad8-17a0-4d12-aa13-f62d481cd534.png)

I've disabled all of Tor's protections and gave it the most liberal permissions that I can on noscript, but nothing changes at all. Both Onionshare and Tor are fully up to date, so I'm not sure what the problem could be. Could be user error, but I really don't know what I could have messed up, I've tried everything that I could come up with.

**Comment by jonathanpecany** [comment]
Same here, it's annoying. Apparently it thinks that javascript is disabled.

**Comment by Aaronvdberg** [comment]
about:config and look if Javascript is disabled , is your onionshare room on private or public?

**Comment by MikeGale** [comment]
Same here:
Windows 10 Pro, 21H1 up to date, 64 bit.
Tor 11.0.2

On chat.  Tried several times.   Failed without any substantial UI on the client, see above.

Exception messages in console, like:
1.  Content Security Policy: The page’s settings blocked the loading of a resource at data: (“default-src”).
2.  The resource from “http.../js/jquery-3.5.1.min.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
Latter 3 instances for different js's.

Attempted quick fixes, on a single instantiation of Onionshare:
1.  In the persistent config file changed disable-csp to true.  Did not work.  The process changed it back to false automatically.
2.  In the template file for chat added "<meta http-equiv="Content-Security-Policy" content="default-src 'self';"/>" .  Did not work.

On another instantiation the chat window, which was persisted, did not appear.

Partial config in persistent store:
  "persistent": {
    "mode": "chat",
    "enabled": true
  },
  "general": {
    "title": null,
    "public": false,
    "autostart_timer": false,
    "autostop_timer": false,
    "service_id": ...
  },
  "share": {
    "autostop_sharing": true,
    "filenames": []
  },
  "receive": {
    "data_dir": ...,
    "webhook_url": null,
    "disable_text": false,
    "disable_files": false
  },
  "website": {
    "disable_csp": false,
    "filenames": []
  },
  "chat": {
    "room": "default"
  }

**Comment by mig5** [comment]
Thinking that maybe this is a Windows-specific thing, I tried on my Windows onionshare dev laptop, but nope - like on Linux and MacOS, it still works perfectly for me :/ unless I use 'Safest' as the security setting in Tor Browser (in which case it obviously doesn't work, because it needs javascript enabled)

**Comment by MikeGale** [comment]
Thanks mig5.
I tried again, and it still fails.  Details follow:
1.  My Tor is on Standard (not Safer or Safest) at present.
2.  I removed my additional meta statement from chat.html template.
3.  I didn't get a chat tab but a "New Tab".  As before.  I "created" a chat service.  On examination later it was the same onion address and credentials as before.  The UI is different but the persisted specification **does in fact** survive.
4.  Again the page lacked the UI.  The console showed the same messages as reported before.  (Chat.js is requested twice, the message is the same.  Two other js's are requested and fail.)
5.  I haven't tried on another machine and don't expect to, it'll run on the machine under test not another (if I can get it working).

**Comment by MikeGale** [comment]
May be unrelated.  On the desktop, the onionshare logo on the shortcut icon has changed to a generic white block today.  Yesterday it was an onionshare image.

**Comment by mig5** [comment]
Hi @MikeGale , if you are around right now, would you be up for testing a Chat room that I set up at my end? I think I've found a fix, and I want to know if it works for you in your Tor browser.

**Comment by mig5** [comment]
Hi @goodusername99 , @bob448 , @jonathanpecany , @MikeGale 

On the assumption that you're all using OnionShare on Windows - and that you were the operator of OnionShare itself (not just a user connecting to a chat in Tor Browser, but running OnionShare the program):

Open Registry Editor (regedit) and open `HKEY_CLASSES_ROOT`.

Click on  `.js` and see if you have a key called 'Content Type' with value 'text/plain' (or at least, something other than text/javascript).

I have no such key, and everything works on Windows for me.

However, as I understand it, other applications might mess with your RegEdit and set the mime type for javascript to text/plain. Perhaps you are all using some common app that has done this without your knowledge.

OnionShare's web server, Flask, uses this RegEdit database for automatically guessing the mimetype of the files OnionShare serves in the web server.

If it is set to text/plain in the registry, then this is why you are experiencing the issue. It's not actually OnionShare's fault.

If you change the registry value to `text/javascript`, or maybe even remove the key altogether (my Windows 10 machine, which is basically brand new, didn't have it), and then close and re-open OnionShare and start a Chat service, it might work fine.

Nonetheless, we can override it in OnionShare to force .js files to have a mime-type of `text/javascript`. I will make a change to that effect, but I'm interested to hear if you all have this registry issue in common.

Further reading:

https://github.com/pallets/flask/issues/1045
https://github.com/golang/go/issues/32350
https://github.com/vearutop/statigz/pull/11
https://github.com/treeverse/lakeFS/issues/2537

**Comment by MikeGale** [comment]
Thanks for that.  It worked for me and that exception message is no longer in the console.

Most excellent.

The console still shows this message, on my machine, "Content Security Policy: The page’s settings blocked the loading of a resource at data: (“default-src”)."
