### ISSUE TITLE
Updated OnionShare to 2.4 on Windows 10 but doesn't start [HELP]

### ISSUE THREAD

**Issue by Cottonwoodhill** [onionshare/onionshare#1451]
Hi @,

I've just updated Onionshare to v.[2.4](https://github.com/onionshare/onionshare/releases/download/v2.4/OnionShare-2.4.msi) but after installation (without error message) it doesn't start anymore, (looping a few  seconds then nothing launches)

I'm running a Win10 machine up to date.

Tried to uninstall Onionshare and resinstalled it again with no more success.

Would you please support if you have any idea what could the issue be?

Thanks in advance.

**Comment by Alexound** [comment]
@Cottonwoodhill @Dennizzzman:

The solution, based on [this discussion](https://stackoverflow.com/questions/20495620/qt-5-1-1-application-failed-to-start-because-platform-plugin-windows-is-missi) is to add and environment variable:
- name: **QT_QPA_PLATFORM_PLUGIN_PATH**
- value: **C:\USERS\your_user_name\AppData\Local\Programs\OnionShare\app_packages\PySide2\plugins\platforms**

@micahflee:
Packaging for Windows should be modified somehow, probably.

**Comment by Cottonwoodhill** [comment]
@Alexound Thank you for your message.
I am using v 2.3.3 for now and will wait until the bug is fixed.
