### ISSUE TITLE
Only installed v2.2 on Whonix Workstation-XFCE

### ISSUE THREAD

**Issue by mountainview7** [onionshare/onionshare#1452]
Hi. I just installed onionshare on Whonix per the directions here: http://www.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion/wiki/OnionShare

Everything worked fine except that it only installed v 2.2 instead of 2.4, so I don't have the chat or upgraded onion URLs. Running inside Oracle VM VirtualBox.

I'm not sure how to force the upgrade to 2.4 - little help?

Thanks

**Comment by mig5** [comment]
Whonix documentation says to `apt install` onionshare, which means you get whatever version is available in Debian itself - likely older than 2.4 indeed. https://www.whonix.org/wiki/OnionShare#Installation_2

Since Whonix doesn't recommend to use the flatpak installation (Tor over Tor), your only real options are:

1) Wait for Debian to ship a newer version of OnionShare (you will probably be waiting a long time), or

2) Don't use a packaged version of OnionShare, and instead run it like a developer would, via a copy of the Git repository. Start by following the small section at https://docs.onionshare.org/2.4/en/develop.html#starting-development , which basically is saying 'follow the README.md in the `cli` folder, then the README.md in the `desktop` folder'. You can then run OnionShare via desktop's `scripts/dev.sh`, or via the CLI, or follow the README to build your own package and install it locally and run it as normal.

I recommend the second option. Good luck!
