### ISSUE TITLE
Arch and stealth error

### ISSUE THREAD

**Issue by se7en-x230** [onionshare/onionshare#1465]
The arch package keeps complaining about tor being too old. No stealth service available. How can I fix that?

**Comment by Stetsed** [comment]
I have had the same error and fixed it by running the flatpak version so it's not a problem with my TOR service(Which is running as a systemd service).

**Comment by se7en-x230** [comment]
Tha ks for the info.
Not a fan of flat/snap pancakes

**Comment by Stetsed** [comment]
> Tha ks for the info. Not a fan of flat/snap pancakes

I agree I don't like them either, I would like to use the arch package more. But it's just a note that it's not a problem with TOR service atleast in my case and if the flatpak works I would guess it would be an issue with the arch package itself in which case you would need to go to the maintainer.

**Comment by mig5** [comment]
It's probably not actually Tor but Stem (which is the Python library for Tor) not supporting Client Auth (stealth).

Unfortunately the Stem project has kind of been abandoned upstream. We had to fork it to add Client Auth support for v3 onions (the ones with the really long URLs).

It's for this reason that Flatpack/Snap works because it bundles our own forked copy of Stem.

One other thing that the Arch developers (or other upstream developers of other Linux distros) can do is ship our fork 'cepa' (https://pypi.org/project/cepa/) as a drop-in replacement for stem. And then adjust their dependency from python-stem to a python-cepa package.

For Linux, I'm afraid those are really the only options (use flatpack/snaps or get your distro's developer to ship cepa instead of stem) until/unless the debacle with Stem gets resolved by the Tor Project.

**Comment by KoNickss** [comment]
could you at least try packaging it as an appimage file? it's the least invasive and annoying of the 3 universal linux package formats

**Comment by mig5** [comment]
Already got an issue for that: https://github.com/onionshare/onionshare/issues?q=is%3Aissue+is%3Aopen+appimage

https://github.com/onionshare/onionshare/issues/1009

**Comment by juergenhoetzel** [comment]
> > Tha ks for the info. Not a fan of flat/snap pancakes
> 
> I agree I don't like them either, I would like to use the arch package more. But it's just a note that it's not a problem with TOR service atleast in my case and if the flatpak works I would guess it would be an issue with the arch package itself in which case you would need to go to the maintainer.

I have created a drop-in-replacement package on AUR: https://aur.archlinux.org/packages/python-cepa

Install using [`yay`](https://github.com/Jguer/yay) or another [AUR helper](https://wiki.archlinux.org/title/AUR_helpers):
```bash
yay -S python-cepa
```
