### ISSUE TITLE
Option to use .NET core website

### ISSUE THREAD

**Issue by MikeGale** [onionshare/onionshare#1490]
I'd like to serve up pages in an Onionshare website from another server.  A .NET core server.

It would be valuable to have guidance about how to do that, or maybe even a sample implementation.

That would apply to other webserver systems too.

Proposal:  Prepare documentation and maybe a sample implementation to achieve that.

**Comment by mig5** [comment]
Sorry, as you probably know, right now OnionShare can only serve a static HTML website directly using its own web server.

We have deliberately not added support for proxying to a remote server. There are a number of reasons:

1) It is more than likely that, without additional effort by yourself, the backend server or its application will serve back content with Host headers that don't use the onion address - meaning your browser makes requests over the 'clear net', e.g not purely 100% onion traffic. Or if not a host/domain name issue, there can be confusion between the protocol (e.g if the backend site is forcing the use of `https://` instead of `http://` - this can also lead to cookie problems that affect functionality of the site.
2) Depending on the threat model or the application, making a request to an onion address which loads 'mixed content' from both onion and non-onion sources, could have security ramifications for the user.
3) The traffic from OnionShare to the backend server would expose the IP address of the OnionShare device to the backend server (although, not the website visitor's IP address). This could place the OnionShare service provider at risk - one of the security features of onions is that *where* they are hosted is meant to be able to be anonymous.

We can't provide many examples because everyone's website is different in terms of the 'host'/mixed content issues. Some applications simply don't make it possible, others have config options or database level changes required.. 

Ultimately what you want to do here, isn't best solved by OnionShare. You would be best to look at the [official instructions for setting up an onion service](https://community.torproject.org/onion-services/setup/), or using the [EOTK](https://github.com/alecmuffett/eotk) (Enterprise Onion Toolkit).

I realize that's probably disappointing but it's just a lot of burden on OnionShare to try to support the many, many corner cases involved with dynamic websites, and what the implications mean depending on different threat models.

If you have trouble setting it up manually with Tor on your .NET server, I bet the Tor community forums would be a great place to get troubleshooting help.

Good luck!

**Comment by MikeGale** [comment]
Thanks for taking the time to answer that so well.

I'm not going to tackle that project now, but will consider it for the future.
