### ISSUE TITLE
Can't connect from Android TOR to any OnionShare server

### ISSUE THREAD

**Issue by AmaryIIis** [onionshare/onionshare#1496]
Not sure if that's on Android TOR or OnionShare, but it's not possible to connect to an OnionShare server (no matter if it's for files or chat) via TOR on Android, not with the regular Android TOR and not with the Alpha Version from Guardian Project via F-Droid.

**Comment by mig5** [comment]
(It's Tor, not TOR)

I'm not sure as I don't have any Android device, but maybe the Tor Browser on Android can't work with private keys? Have you tried an OnionShare share which is in 'public' mode ('Don't use a password'), is there any difference?

**Comment by ShadowSocks12** [comment]
> (It's Tor, not TOR)
> 
> I'm not sure as I don't have any Android device, but maybe the Tor Browser on Android can't work with private keys? Have you tried an OnionShare share which is in 'public' mode ('Don't use a password'), is there any difference?

I used Tor Browser for android and I found that I can connect to onionshare (without private keys), but my only problem is with the "Host a Website" Feature.  https://github.com/onionshare/onionshare/issues/1512

Oh yes and I almost forgot to say that "Receive files" mode doesn't work on Tor browser for android, I mean I made an onionshare link on windows without private keys in "Receive files" mode and then I copied that link and pasted it in Tor Browser for android, and then I press on "Browse" to share files from phone to desktop and then press on "Send Files"...but at the end it says "Nothing submitted" and nothing is sent to the desktop, not even text messages are sent.
I guess that is because maybe "Receive files" mode doesn't support Tor browser on android..I don't know.

**Comment by maltfield** [comment]
I can add a +1 to this.

I know OnionShare doesn't have a client for Android (#567), but I figured I could securely send a file from my phone to my computer by running OnionShare in a QubesOS AppVM running Debian 11 in "receive mode". I did this as follows

```
user@disp9551:~$ onionshare --receive
OnionShare 2.2 | https://onionshare.org/
...
```
I entered the resulting URI (including username & password) into my phone's `Tor Browser` app (org.torproject.torbrowser @ latest version = 11.0.8) installed from the Guardian Project's F-Droid repo

 * https://guardianproject.info/apps/org.torproject.torbrowser/

The `Tor Browser` app loads the "Send Files" website on the Onion Service running on my laptop just fine. And I can click the `Browse...` button and navigate around my Android Filesystem just fine.

But when I select one file (or many files and hit the `Select` button), it does nothing. It still says `No files selected` next to the `Browse...` button.

If I click `Send Files` then it does the `Sending data to initial Tor Node` -> `Waiting for data to finish traversing Tor network ...` just fine. It finishes quickly, and I see `No files uploaded.` appear in green font above the `Browse...` button.

Of course, when I load the site on my `Tor Browser` app, it also reports the connection in OnionShare (I'm using the CLI as shown above, and this is appended to the terminal)

```
127.0.0.1 - - [07/Apr/2022 18:08:08] "POST /upload-ajax HTTP/1.1" 200 -
127.0.0.1 - - [07/Apr/2022 18:08:10] "GET /static/img/ajax.gif HTTP/1.1" 404 -
Apr 07, 06:08PM: Upload of total size 63.0 B is starting
```

**Comment by mig5** [comment]
I think if there are issues with Tor Browser for Android that prevent it uploading files to OnionShare's Receive mode, it's not a problem with OnionShare, but with Tor Browser. This works ok on Onion Browser for iOS for example. Might need an issue opened with Tor Browser for Android upstream.
