### ISSUE TITLE
Updating Onion Address

### ISSUE THREAD

**Issue by gawlinski-com** [onionshare/onionshare#1550]
Hey, hope everyone is doing well.   Big thanks who have worked on this tool, its great.

_(I apologize in advance if this was covered elsewhere.  I tried searching docs & online for an answer, but it is still unclear.)_

I am trying to change my onion address.  I was able to obtain a "hostname" , "hs_ed25519_public_key", & "hs_ed25519_secret_key" for the address I want to use.  

I am assuming I just need to update my JSON file, located in the "persistent" folder.  **But I am not really sure what goes where.**  I assume the General/ServiceID is the address i want to use.  But it seems there is a client private key, a regular priv key, and a public key.

Also noticed the current/default fields in these keys are normal characters.  When I open my own public/private keys with the new onion address I want to use, the characters don't look right.  When I try to open the document "hs_ed25519_secret_key" it says there are invalid characters, so any edits could corrupt the file.  Is this an issue?

Sorry if this is covered elsewhere.  I know your time is important, but would appreciate on how to change the onion address.

**Comment by mig5** [comment]
If you have an onion address (generated elsewhere) that you want to use with OnionShare, yes, you'll need to put that onion address in the field `general['service_id']`. Note that it doesn't include the `.onion` suffix.

You will also need to update the `onion['private_key']` value. This value is a base64-encoded version of the ed25519 private key. So you will need to work out how to generate that from your `hs_ed25519_secret_key`, which is not an ASCII file and hence the 'invalid characters'.

Try something like `dd if=hs_ed25519_secret_key bs=1 skip=32 | base64` . The full private_key value might cross two lines, put it all on one line - it's probably about 89 characters..

The client_auth pub/priv keys are for Client Authentication and aren't cryptographically related to the onion private key/hostname. You can leave those as they are (or maybe they are empty because it's a public onion service anyway).

**Comment by gawlinski-com** [comment]
thank you mig5 I really appreciate the quick response and feedback.  let me try this and I'll keep you updated

**Comment by gawlinski-com** [comment]
Hi mig5

Strangely enough - when making the recommended changes, I don't even get Onion Share to open up now.  The hourglass will spin for a second, but then nothing will happen.

pastebin.com/A9mVXDnS

^^
This is the system I am on.  Do you think I should delete the configuration file and try again? Or is there a potential error message I can look at?

_(sorry for the weird question, I am new to Linux and encryption and trying to learn how to set this up)_

I appreciate your time and help.

**Comment by mig5** [comment]
@gawlinski-com it's hard to say what the issue might be. Could you try running OnionShare from the command line with the `--verbose` flag?

You should be able to do it like this:

```
onionshare-cli --persistent ~/.config/onionshare/persistent/YOUR-PERSISTENCE-FILE.json --verbose PATH-TO-SOME-ARBITRARY-FILE
```

In the above command, adjust the `YOUR-PERSISTENCE-FILE.json` to the real name of the persistent json settings file that you had modified. And then change `PATH-TO-SOME-ARBITRARY-FILE` to a real arbitrary file that you might want to share. 

I am assuming that this OnionShare persistent tab was in 'share' mode and not 'receive' or 'website' mode.

Please note that the output might expose information such as the onion service address, which might not be safe to share here. You may need to mask some of the output before sharing, and/or don't share it via Github but via another service such as Keybase (per my comment below). But more importantly, the output might simply show a clear Python exception message which is the more valuable info here for debugging.

I would also love to see the contents of the json file but you obviously should not share the private key settings nor perhaps the true onion address. If there is a way for you to mask the contents of the file and then share it with me, perhaps that would be useful - you could sign up to Keybase.io and share it with me (I am @mig5 there, too) if you do not want to share the info on a service such as Github.

Since you are new to Linux and encryption, if in doubt do not share any of the output here but perhaps with me in private, via Keybase, and recommended to remove any info about the .onion address or the private key etc from the json or any output.

**Comment by gawlinski-com** [comment]
Hi @mig5 -- I know you are under no obligation to contribute or support this, so I really appreciate your time.

I am not hosting anything overly private, so I don't mind sharing the onion address.  I did remove the private_key though from the json file.  What is interest, is the private key that was generated, has a combination of upper and lower characters.  Whereas the default one that was working with Onion Share was all capital I believe.

Here is the error when trying to run from the command line:
https://pastebin.com/vVBk1ac2

And here is the json file I have:
https://pastebin.com/eBqX877p

Hope this helps.  Let me know if I can provide any other details.

**Comment by mig5** [comment]
@gawlinski-com hmm, that python import error is unexpected. I see you are using Flatpak, so I just installed the Flatpak package on my Debian 11 machine and it worked ok with a persistent json file...

```
user@onionshare:~$ /var/lib/flatpak/app/org.onionshare.OnionShare/x86_64/stable/0cf9cdd6f0f89b7075e2b800c995b7863a1dc41569e891d56c1098703eb9970f/files/bin/onionshare-cli --persistent ~/.config/onionshare/persistent/whinny-jokingly-wrath.json --verbose ~/test.py
╭───────────────────────────────────────────╮
│    *            ▄▄█████▄▄            *    │
│               ▄████▀▀▀████▄     *         │
│              ▀▀█▀       ▀██▄              │
│      *      ▄█▄          ▀██▄             │
│           ▄█████▄         ███        -+-  │
│             ███         ▀█████▀           │
│             ▀██▄          ▀█▀             │
│         *    ▀██▄       ▄█▄▄     *        │
│ *             ▀████▄▄▄████▀               │
│                 ▀▀█████▀▀                 │
│             -+-                     *     │
│   ▄▀▄               ▄▀▀ █                 │
│   █ █     ▀         ▀▄  █                 │
│   █ █ █▀▄ █ ▄▀▄ █▀▄  ▀▄ █▀▄ ▄▀▄ █▄▀ ▄█▄   │
│   ▀▄▀ █ █ █ ▀▄▀ █ █ ▄▄▀ █ █ ▀▄█ █   ▀▄▄   │
│                                           │
│                   v2.5                    │
│                                           │
│          https://onionshare.org/          │
╰───────────────────────────────────────────╯

[Mar 29 2022 08:11:59] Settings.__init__
[Mar 29 2022 08:11:59] Settings.load
[Mar 29 2022 08:11:59] Settings.load: Trying to load /home/user/.config/onionshare/onionshare.json
[Mar 29 2022 08:11:59] Common.get_resource_path: filename=wordlist.txt
[Mar 29 2022 08:11:59] Common.get_resource_path: filename=wordlist.txt, path=/home/user/.local/lib/python3.9/site-packages/onionshare_cli/resources/wordlist.txt
[Mar 29 2022 08:11:59] ModeSettings.load: loaded /home/user/.config/onionshare/persistent/whinny-jokingly-wrath.json
[Mar 29 2022 08:11:59] ModeSettings.set: updating bullion-activity-cedar: persistent.enabled = True
[Mar 29 2022 08:11:59] ModeSettings.set: updating bullion-activity-cedar: share.filenames = ['/home/user/OnionShare/2022-03-07/163811236082-message.txt']
[Mar 29 2022 08:11:59] Web.__init__: is_gui=False, mode=share
[Mar 29 2022 08:11:59] Common.get_resource_path: filename=static
[Mar 29 2022 08:11:59] Common.get_resource_path: filename=static, path=/home/user/.local/lib/python3.9/site-packages/onionshare_cli/resources/static
[Mar 29 2022 08:11:59] Common.get_resource_path: filename=templates
[Mar 29 2022 08:11:59] Common.get_resource_path: filename=templates, path=/home/user/.local/lib/python3.9/site-packages/onionshare_cli/resources/templates
[Mar 29 2022 08:11:59] Web.generate_static_url_path: new static_url_path is /static_utiwdggz2j77ocwjdxmijromq4
[Mar 29 2022 08:11:59] ShareModeWeb.init
[Mar 29 2022 08:11:59] Onion.__init__
[Mar 29 2022 08:11:59] Settings.__init__
[Mar 29 2022 08:11:59] Settings.load
[Mar 29 2022 08:11:59] Settings.load: Trying to load /home/user/.config/onionshare/onionshare.json
[Mar 29 2022 08:11:59] Onion.connect: connection_type=bundled
[Mar 29 2022 08:11:59] Onion.connect: tor_data_directory_name=/home/user/.config/onionshare/tmp/tmpxcan96nj
[Mar 29 2022 08:11:59] Common.get_resource_path: filename=torrc_template
[Mar 29 2022 08:11:59] Common.get_resource_path: filename=torrc_template, path=/home/user/.local/lib/python3.9/site-packages/onionshare_cli/resources/torrc_template
[Mar 29 2022 08:11:59] Onion.connect: Writing torrc template file
[Mar 29 2022 08:11:59] Onion.connect: starting /usr/bin/tor subprocess
[Mar 29 2022 08:11:59] Onion.connect: tor pid: 3143
[Mar 29 2022 08:12:01] Onion.connect: authenticating to tor controller
Connecting to the Tor network: 100% - Done
[Mar 29 2022 08:12:45] Onion.connect: Connected to tor 0.4.6.10
[Mar 29 2022 08:12:45] Settings.load
[Mar 29 2022 08:12:45] Settings.load: Trying to load /home/user/.config/onionshare/onionshare.json
[Mar 29 2022 08:12:45] OnionShare.__init__
[Mar 29 2022 08:12:45] OnionShare.start_onion_service
[Mar 29 2022 08:12:45] Onion.start_onion_service: port=17648
[Mar 29 2022 08:12:45] Onion.start_onion_service: key_type=ED25519-V3
[Mar 29 2022 08:12:54] ModeSettings.set: updating bullion-activity-cedar: general.service_id = eyotfzjqgb4ib7mc24soolviryqeoyhmtpruvyuoy5g4rcecvnv4hrad
[Mar 29 2022 08:12:54] ModeSettings.set: updating bullion-activity-cedar: onion.client_auth_priv_key = CW6CPSSVGFBYZ5X2L3O7NFU362X2JVI7AIML7KWVFQLL4BQHJC6A
[Mar 29 2022 08:12:54] ModeSettings.set: updating bullion-activity-cedar: onion.client_auth_pub_key = ILZCYGF6RMM7NMQPDMWMNBZN6B3ZZVS5N5AXRB7R4GHSEVDWUZ3Q
Compressing files.
[Mar 29 2022 08:12:54] ShareModeWeb.init
[Mar 29 2022 08:12:54] ShareModeWeb.set_file_info_custom
[Mar 29 2022 08:12:54] ShareModeWeb.build_zipfile_list: filenames=['/home/user/OnionShare/2022-03-07/163811236082-message.txt']
[Mar 29 2022 08:12:54] Web.start: port=17648
 * Running on http://127.0.0.1:17648/ (Press CTRL+C to quit)

Give this address and private key to the recipient:
http://eyotfzjqgb4ib7mc24soolviryqeoyhmtpruvyuoy5g4rcecvnv4hrad.onion
Private key: CW6CPSSVGFBYZ5X2L3O7NFU362X2JVI7AIML7KWVFQLL4BQHJC6A

Press Ctrl+C to stop the server
```


What about if you try this?

```
/var/lib/flatpak/app/org.onionshare.OnionShare/x86_64/stable/0cf9cdd6f0f89b7075e2b800c995b7863a1dc41569e891d56c1098703eb9970f/export/bin/org.onionshare.OnionShare --verbose
```

I am not sure the python error is the cause of the OnionShare not starting or if it's a different problem :/ you could also try re-installing the app but it shouldn't be necessary..

**Comment by gawlinski-com** [comment]
Okay.  This error message looks a bit different.

Let me know if this is more helpful:
https://pastebin.com/t5EJJyBM

Otherwise, if the above doesn't mean much.  I can start over with a fresh set of vanity onion addresses.  I generated a few extra that I don't plan on using, so happy to share the private keys and walk you through what I have been doing to see if it is a user error on my part.

**Comment by mig5** [comment]
Hi again @gawlinski-com 

I think you must have a 'lock' file in your file system which is what is blocking the UI from loading.

Look in the `~/.config/onionshare/` folder and if you find a `lock` file, please remove it, and then try and open OnionShare as normal.

**Comment by gawlinski-com** [comment]
That did it!  Everything is working great.  Thank you very much!

**Comment by mig5** [comment]
Glad to hear it!
