### ISSUE TITLE
[HELP] Support client authentification : False

### ISSUE THREAD

**Issue by Cottonwoodhill** [onionshare/onionshare#1573]
Hi!

I can't transfert files as I get that error.

![Ca4pture](https://user-images.githubusercontent.com/37047745/163420435-e987a653-dbe1-41d5-8526-d4fe99a33e76.JPG)

Onionshare doesn't accept the authentification code.

Please help.

Thanks

Debian based / Onionshare ver 2.3.3

Will an update to ver 2.5 fixe that?

**Comment by Cottonwoodhill** [comment]
Well, using Whonix I don't know how to upgrade ver 2.3.3 to 2.5.
Maybe this would fix that isssue?
How to upgrade OnionShare on that distribution?
Thanks for your support.

**Comment by mig5** [comment]
The issue here is the version of Stem (the Python library for Tor) on that OS is too old to support Client Authentication.

The OnionShare core developers aren't the ones making .deb packages for Debian/Ubuntu/Whonix. If you are using apt to install onionshare, you're likely to get a really old version and we can't do anything about that I'm afraid. Getting on to the latest version of OnionShare requires the Debian/Ubuntu/Whonix people to package a .deb file for it, and Debian tends to lag behind versions for years because it 'freezes' the versions very early in their release lifecycle.

You'll need to either:

1) Install the flatpak or snap packages we release for Linux, or
2) Install onionshare-cli via pip and use the CLI version, or
3) Wait for a newer version of Debian/Whonix that might have a newer version of Tor/Stem/OnionShare, or
4) Build OnionShare from source, per the README in the 'cli' and 'desktop' directories of our repository, or
5) Just use OnionShare but without Client Authentication enabled (less secure, but if you keep the onion address very secret, it should not be 'discoverable', per the design of 'v3 onion' addresses)

**Comment by Cottonwoodhill** [comment]
Have been using this method :

5. Just use OnionShare but without Client Authentication enabled (less secure, but if you keep the onion address very secret, it should not be 'discoverable', per the design of 'v3 onion' addresses)

Don't feel good with it but at least I can use OnionShare with some features it is supposed to provide.

Thanks
