### ISSUE TITLE
Provide .deb and .rpm binaries for Linux

### ISSUE THREAD

**Issue by Destroyinator69420** [onionshare/onionshare#1631]
Hello Micah Lee,

I hope I got your name right.
I am switching am considering switching to linux and one of the main barriers is software support. The linux binaries for onionshare are lacking. Leaving it up to the package repositories to compile onionshare leads them to fail to update to the latest version as soon as possible. One should not be using old versions of onionshare due to its critical nature, and I do not like flatpack or snap, each for their own reasons. When will you provide .deb and .rpm installer files for Linux.

All the best,
Destroyer2

**Comment by hwittenborn** [comment]
Would [makedeb](https://makedeb.org) be of any interest for the Debian packaging? It would allow publishing as both a .Deb file and to the [AUR](https://aur.archlinux.org) from a single source, and would probably be easier to maintain than a standard Debian package just considering the Debian side of things.

**Comment by mig5** [comment]
It was not possible to provide .deb any more because the versions of libraries/dependencies we need, was not always readily available as a .deb dependency.

I also don't like Flatpak/Snap personally, but unfortunately, I don't see a way forward to supporting an onionshare .deb that is up to date with the latest release. 

You can see that even the Debian developers are struggling to package newer versions: https://github.com/onionshare/onionshare/issues/1871 . If they can't do it with their extensive expertise, there is little hope the OnionShare team could do any different.

You can also run OnionShare directly from source code without needing a package at all (and that's how I tend to use it). It's not super easy, but it is a one-time thing to build the dependencies, and then it works, on Debian. https://github.com/onionshare/onionshare/blob/main/desktop/README.md
