### ISSUE TITLE
Status of CVEs ? 

### ISSUE THREAD

**Issue by nodens** [onionshare/onionshare#1633]
Hi,

as part of the pkg-privacy-maintainers team, I maintain onionshare in Debian (and indirectly for Tails).

We're having trouble determining for which version those CVEs apply:

 - https://security-tracker.debian.org/tracker/CVE-2021-41867
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-41867
  - https://security-tracker.debian.org/tracker/CVE-2021-41868
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-41868
  - https://security-tracker.debian.org/tracker/CVE-2022-21688
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21688
  - https://security-tracker.debian.org/tracker/CVE-2022-21689
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21689
  - https://security-tracker.debian.org/tracker/CVE-2022-21690
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21690
  - https://security-tracker.debian.org/tracker/CVE-2022-21691
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21691
  - https://security-tracker.debian.org/tracker/CVE-2022-21692
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21692
  - https://security-tracker.debian.org/tracker/CVE-2022-21693
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21693
  - https://security-tracker.debian.org/tracker/CVE-2022-21694
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21694
  - https://security-tracker.debian.org/tracker/CVE-2022-21695
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21695
  - https://security-tracker.debian.org/tracker/CVE-2022-21696
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21696

Also seen at https://github.com/onionshare/onionshare/security/advisories

While my understanding is they were all fixed in 2.4 (it states <2.4), the lack of "patched version" in the fields is confusing. Also, I see no reference to those in the git log…

Could you please confirm whether those CVE are fixed since 2.4 (or since which version they are fixed) or not ? Or which ?

Ideally, updating the advisories to make it unambiguous in the process. :)

Debian BTS entry: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014966

Thanks!

**Comment by mig5** [comment]
Hi Clément,

On Sun, Oct 23, 2022 at 09:25:28AM -0700, Clément Hermann wrote:
> We're having trouble determining for which version those CVEs apply:
>
> https://github.com/onionshare/onionshare/security/advisories
>
> While my understanding is they were all fixed in 2.4 (it states <2.4), the lack of "patched version" in the fields is confusing. Also, I see no reference to those in the git log…
>
> Could you please confirm whether those CVE are fixed since 2.4 (or since which version they are fixed) or not ? Or which ?

Sorry for the confusion.

These vulnerabilities were all actually fixed in 2.5, please see [the changelog](https://github.com/onionshare/onionshare/blob/main/CHANGELOG.md#25)

> Ideally, updating the advisories to make it unambiguous in the process. :)

Yes, I'll update these advisories to fix the affected versions, and note that 2.5 is the patched version for all these issues.

Only affected >= 2.3 - < 2.5: CVE-2021-41867, CVE-2022-21691, CVE-2022-21695, CVE-2022-21696
Only affected >= 2.2 - < 2.5: CVE-2022-21694
Only affected >=2.0 - < 2.5: CVE-2022-21689, CVE-2021-41868
All versions < 2.5: CVE-2022-21690, and possibly depending on the Qt version, CVE-2022-21688


https://github.com/onionshare/onionshare/security/advisories/GHSA-jgm9-xpfj-4fq6 is a complicated one, as a [fix](https://github.com/onionshare/onionshare/pull/1474) we reduced the scope of access for Flatpak but you could argue that on 'native' Debian the whole file system, or at least the parts accessible to the user running OnionShare, is available not even in read-only mode. I'm not sure there's really a 'fix' for the deb package.

I hope this clears up some of the confusion.

**Comment by mig5** [comment]
Edited the above response to note that https://github.com/advisories/GHSA-7g47-xxff-9p85 was fixed/mitigated in 2.4 by switching to using Tor's Client Auth for authentication in OnionShare, rather than HTTP auth. I am not sure of the exact release that introduced the issue but it is a Receive Mode issue, thus 2.0 or higher.

**Comment by geor-g** [comment]
> [GHSA-jgm9-xpfj-4fq6](https://github.com/onionshare/onionshare/security/advisories/GHSA-jgm9-xpfj-4fq6) is a complicated one, as a [fix](https://github.com/onionshare/onionshare/pull/1474) we reduced the scope of access for Flatpak but you could argue that on 'native' Debian the whole file system, or at least the parts accessible to the user running OnionShare, is available not even in read-only mode. I'm not sure there's really a 'fix' for the deb package.

It might make sense to rely on, for example, Apparmor, to limit filesystem access.

**Comment by nodens** [comment]
> Edited the above response to note that https://github.com/advisories/GHSA-7g47-xxff-9p85 was fixed/mitigated in 2.4 by switching to using Tor's Client Auth for authentication in OnionShare, rather than HTTP auth. I am not sure of the exact release that introduced the issue but it is a Receive Mode issue, thus 2.0 at least.
>
> All the others were fixed in 2.5.


Thanks for the clarification! I did suppose the 2.5 version at least was ok, but it's much better to have the detail. Now we can decide what to do about the version in stable.

>> [GHSA-jgm9-xpfj-4fq6](https://github.com/onionshare/onionshare/security/advisories/GHSA-jgm9-xpfj-4fq6) is a complicated >> one, as a https://github.com/onionshare/onionshare/pull/1474 we reduced the scope of access for Flatpak but you could argue >> that on 'native' Debian the whole file system, or at least the parts accessible to the user running OnionShare, is available not >> even in read-only mode. I'm not sure there's really a 'fix' for the deb package.

Indeed, this is a "vulnerability" (more "extended attack surface IMO) that applies only to Flatpak.

> It might make sense to rely on, for example, Apparmor, to limit filesystem access.

Yes. It's on the TODO list. :)

**Comment by nodens** [comment]
Oops, turns out I closed it a bit early. Could I have further clarification on this one ?
> Only affected >=2.0 - < 2.4: https://github.com/advisories/GHSA-7g47-xxff-9p85 (Receive mode bug, fixed by changing the authentication from HTTP auth to using Client Auth in Tor itself)

The advisory says 2.3. Does it affect >=2.0 or >=2.3 ? Since it's a critical one and we still ship 2.2 in stable that's an important one… :)

**Comment by mig5** [comment]
@nodens 

Sorry, upon further inspection, it unfortunately does affect >= 2.2 (inclusive of 2.2). I just reproduced it on Debian stable.

Prior to 2.2, there was no HTTP auth at all (there was instead a 'slug' at the end of the URL, which had to be known already by the attacker).

In 2.2, we replaced the slug route with HTTP auth, and likely therefore introduced this issue for Receive Mode.

We then fixed it in 2.4 by switching again to Tor Client Auth keys, removing HTTP auth.

Here's where I think it will get super awkward for Debian: it looks like you'll need a fix for stable, and that's quite a difficult one, because the 'fix' (rather, the pivot to a different authentication mechanism) relied on a newer version of Stem that adds Client Auth support for v3 onions (which led us to forking Stem for a while).

And astonishingly, that same fix only landed in Stem upstream just a couple of weeks ago since the upstream maintainer had given up maintaining (and didn't hand over to anyone at TP) - as I think you know already. https://lists.torproject.org/pipermail/tor-dev/2022-September/014776.html

I think your options are:

1) Drop onionshare altogether as not being able to fix it (since I assume you can't release a new version of Stem 1.8.1 in Debian Stable?)

2) Try to figure out how to make HTTP auth fire in Flask before the upload logic (which we couldn't do or didn't have time, so just switched away from HTTP auth)

3) Drop the Receive Mode support altogether in Debian's version of 2.2

None of which are ideal.. it would be nice to figure out 2) but it's so old now and I don't know how to do it. I wonder if @micahflee or @SaptakS have any ideas.

**Comment by nodens** [comment]
> Sorry, upon further inspection, it unfortunately does affect >= 2.2 (inclusive of 2.2). I just reproduced it on Debian stable. I think the final report by Github was 2.3 just because that's what the researcher said they used. I can't seem to edit that advisory as we didn't make it ourselves.

I see. Thanks for actually testing it!

> Here's where I think it will get super awkward for Debian: it looks like you'll need a fix for stable, and that's quite a difficult one, because the 'fix' (rather, the pivot to a different authentication mechanism) relied on a newer version of Stem that adds Client Auth support for v3 onions (which led us to forking Stem for a while).
> 
> And astonishingly, that same fix only landed in Stem upstream just a couple of weeks ago since the upstream maintainer had given up maintaining (and it seems TP didn't take up ongoing maintenance of it, at least in practice) - as I think you know already. https://lists.torproject.org/pipermail/tor-dev/2022-September/014776.html

Yes, I'm aware, I'm the same nodens mentionned in this post :)

> I think your options are:
> 
>     1. Drop onionshare altogether as not being able to fix it (since I assume you can't release a new version of Stem 1.8.1 in Debian Stable?)
> 
>     2. Try to figure out how to make HTTP auth fire in Flask before the upload logic (which we couldn't do or didn't have time, so just switched away from HTTP auth)
> 
>     3. Drop the Receive Mode support altogether in Debian's version of 2.2
> 
> 
> None of which are ideal.. it would be nice to figure out 2) but it's so old now and I don't know how to do it. I wonder if @micahflee or @SaptakS have any ideas.

Ack. We'll figure something out. Updating onionshare to 2.5 in stable is not completely off the table, as Bullseye has python-stem 1.8.0, and 1.8.1, as you said, is more a maintainance update than a new release.

> One other thing (it's not a lot, but saying it as a slight mitigation): remembering that onion 'v3' addresses are not meant to be practically enumerable (the Directory Authorities, I believe, can't 'leak' or discover them) unlike v2 addresses, an attacker still has to learn the v3 onion address somehow, in order to exploit it. This would still mean requiring exposure of the onion address (or an incredibly lucky guess of the 52 character URL) as a pre-condition for exploit. (That said, there is the 'Use legacy addresses' option in 2.2, which switches back to v2 onions, so that's still pretty bad)
> 
> In that sense, 'Privileges required: None' is perhaps debatable when in the context of v3 onion addresses - knowing an otherwise unguessable, not-leakable-by-design address is in some way a privilege that is not trivial to achieve. A counter-argument of course is that this could be considered 'security through obscurity' and it would not help v2 addresses which can be discovered.
> 
> The vuln is also limited to uploading new files but not reading, modifying, overwriting existing ones.

Thanks for confirming that! :)

**Comment by SaptakS** [comment]
I agree with @mig5 . The Stem situation is a bit messy so not sure what's the best path. Definitely if updating to 2.5 is an option, that might be good, though I think we started using stem 1.8.1 instead of our fork from OnionShare 2.6? @mig5 correct me if I am wrong.

**Comment by nodens** [comment]
Well, one option would be to leave [CVE-2021-41868](https://github.com/advisories/GHSA-7g47-xxff-9p85) unfixed in Bullseye, as an edge case, and provide a backport for users needing secure auth.

Not the best solution, for sure, but upgrading to 2.5 in stable has some non-trivial implications. The other fixes can indeed be backported (This is currently in discussion at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014966).

Wrt. the Stem situation, ideally Tor Project would hand over the maintenance. They're willing to do so if someone is "serious about it", I'll file another issue about that.

**Comment by nodens** [comment]
Seems like I failed to update this issue… The fixes that could make it in Bullseye are there, and onionshare is up to date in Bookworm, too.
