### ISSUE TITLE
Allow Upload and Download using Share Mode

### ISSUE THREAD

**Issue by oe3gwu** [onionshare/onionshare#1847]
I have the need to sometimes create a "Drop" Server for quick and dirty file sharing in a small team. Currently I use 2 instances where upload and download are seperated, but this is sometimes annoying because I have to monitor all this. It would be nice to have a allow upload flag in the sharing section.

**Comment by mig5** [comment]
I'm going to close this not because it is invalid but because we have an older issue that raises the same question: https://github.com/onionshare/onionshare/issues/1517

I don't know how feasible it would be without a major refactor, but anyone interested in working on it could discuss further in that issue. One thing that issue suggests is using a route-based approach (/chat, /receive, /share) which might make it more feasible.

Thanks for your interest!
