### ISSUE TITLE
python-stem is obsolete

### ISSUE THREAD

**Issue by coogor** [onionshare/onionshare#1851]
Any plan to switch to the successor cepa?

**Comment by SaptakS** [comment]
We did create cepa as a fork of stem because of the same reason that python-stem is obsolete, but if I remember correctly, there was some packaging issues. @mig5 or @micahflee might have more context on that.

**Comment by mig5** [comment]
Yeah, it was *us* that created the `cepa` fork. We did this because we ourselves wrote the feature to attach Client Auth to v3 onions, which we submitted to Stem at the time. 

Due to the upstream issue with Stem's maintainer leaving, it was taking too long/uncertain as to whether they'd make a new release to contain that new feature.

So we released `cepa` as an interim measure to allow us to release OnionShare with v3 Client Auth support.

Later, Stem *did* make a new release that contained our change, so we went back to using Stem. Cepa has not been touched since.

The question of maintenance of Stem and OnionShare has come up before: https://github.com/onionshare/onionshare/issues/1634 . But I am not sure the team has the capacity to maintain both projects (maintaining OnionShare is itself already proving a challenge).

There seems to have been more activity on Stem of late, with even a 1.x release within the last 8-9 months. Maybe things will end up ok upstream.
