### ISSUE TITLE
OnionShare onboarding process

### ISSUE THREAD

**Issue by micahflee** [onionshare/onionshare#436]
The very first time you run OnionShare (e.g. if there isn't a settings file yet) there should be an onboarding process that let's you choose how you connect to Tor, before trying to connect. This should also allow the user to set a bridge (#435).

The onboarding process should also briefly explain to new users how to use OnionShare.

**Comment by mig5** [comment]
Maybe a welcome dialog that then offers to take the user to the Settings would be ideal, as then you could avoid too much code by just loading the SettingsDialog for Tor config setup?

There should perhaps also be a --skip-intro flag for the GUI. Thinking about automated tests, where there may not be a .json file at all.

**Comment by mig5** [comment]
@micahflee, rather than get too creative, could it be as simple as showing the dialog in the attached screenshot if no json exists? 

<img width="456" alt="screen shot 2017-06-02 at 12 33 08 pm" src="https://cloud.githubusercontent.com/assets/99173/26708586/fcfbbeb0-478f-11e7-8a0c-7ce689bb1071.png">

(Clicking OK simply takes you to the Settings dialog to complete configuration).

If so this is a tiny patch that I am happy to provide.

The bridge options could then just be incorporated into the Settings dialog alongside the other Tor settings.

**Comment by bmintz** [comment]
This should also be do-able over the CLI, as currently everything else is, too.

**Comment by mig5** [comment]
I'm going to close this old issue because it has overlapped with the 'Quickstart' and auto-bridge-configuration work that is coming in #1420 and related.
