### ISSUE TITLE
Add option to encrypt file and add options for different types of archives or no archive at all

### ISSUE THREAD

**Issue by catskillmarina** [onionshare/onionshare#684]
Add option to encrypt file and add options for different types of archives or no archive at all

**Comment by micahflee** [comment]
This is related to #663. It's only feasible to not have an archive at all when you're sending a single file. If you're sending multiple files, they need to somehow bundled into a single download. #663, when implemented, will simple not zip up the file if you're sending a single file, but will zip up multiple files still.

The reason OnionShare uses zip for archives is because there's unzipping software built-in and pre-installed in Windows, macOS, and major Linux distros. What would be the benefit of adding different types of archives?

I've also considered adding encryption, but this opens up a lot of questions. First: symmetric or public key encryption? The main standard for public key encrypt is OpenPGP, and adding support for this into OnionShare would include a *lot* of extra code, including key management and stuff, and I'm not sure it makes sense since there are other tools specifically for doing this.

Symmetric encryption would be simple enough -- it would just ask for a passphrase when you start sharing, but the receiver will need to also have the right software to decrypt this on their end, and at the moment the receiver only uses Tor Browser. But also, if you use symmetric encryption, you're going to have to communicate the passphrase somehow, and if you communicate the passphrase in the same way you communicate the OnionShare URL, then it kind of defeats the purpose. An attacker that is able to learn the OnionShare URL will also be able to download and decrypt the data.

So there are some big usability issues with adding a layer of encryption on shares. Since onion services are end-to-end encrypted anyway, there aren't many benefits to it either, especially once v3 onion services are supported and the onion service crypto is stronger.

But if you can explain the use-case more for options to encrypt the file I'd be into considering it again.
