### ISSUE TITLE
Add a flag for receiver mode

### ISSUE THREAD

**Issue by Hainish** [onionshare/onionshare#97]
When you run onionshare in receiver mode, you should present the client with an upload box to send a file to the server.  This effectively reverses the flow of traffic from the current standard.

**Comment by micahflee** [comment]
I need to make sure to include security warnings about receive mode, basically warning about phishing and malicious documents. I'm planning on not restricting upload file types, so anything goes, and some users might not be aware of the danger.

**Comment by micahflee** [comment]
I've run into a thorny issue. When running in receive mode, it would be nice if OnionShare could display the upload progress on the _server_ side -- that is, the actual CLI or GUI app, not the web app. This turns out to be much trickier than it first seems.

By the time the flask route gets executed, the entire file has already been uploaded. I've been digging into several options, including writing WSGI middleware to intercept the request before flask sees it and then stream parsing the incoming `multipart/form-data` object... but that has its own loads of problems, and is very complex.

The most promising route now appears to be what is mentioned in [this comment](https://stackoverflow.com/questions/20015550/read-file-data-without-saving-it-in-flask/42405115#42405115) on stackoverflow. Basically, I can create my own class that inherits from `flask.Request`, and override the `_get_file_stream` method. While flask parses multipart file uploads, this gets called for each file. Here are the docs for this method:

```
_get_file_stream(self, total_content_length, content_type, filename=None, content_length=None)
    Called to get a stream for the file upload.
    
    This must provide a file-like class with `read()`, `readline()`
    and `seek()` methods that is both writeable and readable.
    
    The default implementation returns a temporary file if the total
    content length is higher than 500KB.  Because many browsers do not
    provide a content length for the files only the total content
    length matters.
    
    :param total_content_length: the total content length of all the
                                 data in the request combined.  This value
                                 is guaranteed to be there.
    :param content_type: the mimetype of the uploaded file.
    :param filename: the filename of the uploaded file.  May be `None`.
    :param content_length: the length of this file.  This value is usually
                           not provided because webbrowsers do not provide
                           this value.
```

So, I can write my own version of this method that tracks how much data is written for each file, and communicates this to the user.

In my tests, when uploading multiple files, I don't get a `content_length` for each file (using Tor Browser), which means there's actually no way of knowing how big each file is until that file is done uploading. I think. Anyway I'll have to dig into this further, but this strategy of overriding `Request._get_file_stream` seems promising.

**Comment by micahflee** [comment]
Nice, got it working. Now all I have left is the GUI and thorough testing.
